### PR TITLE
refactor tests

### PR DESCRIPTION
**Pull request by jeffreyhanson**
This PR refactors the unit tests. Briefly, I've split each test into it's own `test_that(...)` call so that (i) we can see test descriptions when they fail when running `test()`, and (ii) each test is independent of other tests so that one failing test won't affect other tests. I have also removed `testthat::` code before the functions from the testthat package because the test code involves calling `library(testthat)` before the tests are running -- which means that all testthat functions are available in the global namespace when running tests (see [here](https://github.com/dimitri-justeau/restoptr/blob/master/tests/testthat.R#L2)). What do you think? Note that one of the tests now fails, but this should be ok when #44 is merged (because it assumes that text is printed to console using `message()`).

### CODE REVIEW

**Comment by dimitri-justeau** [comment]
I'm totally ok with this PR ! But before merging, we should resolve the question I asked in https://github.com/dimitri-justeau/restoptr/pull/44#issuecomment-1105462359 about using `message()` in `print()`

**Comment by jeffreyhanson** [comment]
Sounds good!

**Comment by jeffreyhanson** [comment]
Once the othe PR's been merged, I'll resolve these conflicts.

**Review by dimitri-justeau — APPROVED** [review]

**Comment by dimitri-justeau** [comment]
Hi @jeffreyhanson! I took the liberty to update and merge this branch according to the master's previous modifications! Do not hesitate to tell me if you feel like something is missing!

**Pull request merged**
