### PR TITLE
fix #43

### LINKED ISSUE #43: message() instead of cat()
It's generally recommended to use `message()` instead of `cat()` for displaying messages in packages (e.g. within the R/solve.R file). This is because the former can easily be suppressed using `suppressMessages()` if desired, whereas silencing `cat()` is not always straightforward. I'm happy to submit a PR with this if that would be helpful?

### PR DESCRIPTION
**Pull request by jeffreyhanson**
Replace cat() with message(), per #43

### CODE REVIEW

**Comment by jeffreyhanson** [comment]
Sorry, I feel like I'm missing something  important - the tests that involve solving the problem don't appear to pass when running them on my computer (i.e., I see the `java.lang.NoSuchMethodError: <init>` error).

**Comment by dimitri-justeau** [comment]
> Replace cat() with message(), per #43

According to https://stackoverflow.com/questions/36699272/why-is-message-a-better-choice-than-print-in-r-for-writing-a-package, `cat()` should be used in the `print()` method. I agree with using `message` in the `solve()` method, as they are informational messages, and independent of the method's behaviour. However, as the behaviour of the `print()` method is to display information to stdout, it seems odd to me to use message, as `suppress messages()` would alter the behaviour of the method. Is it ok for you to modify this PR to only use `message()` in `solve()` ?

**Comment by jeffreyhanson** [comment]
Interesting - thanks for looking into this! Yeah, that makes sense to me. I'll update this so that the print methods using `cat()`.

**Review by dimitri-justeau — APPROVED** [review]

**Comment by dimitri-justeau** [comment]
Thank you !!

**Comment by dimitri-justeau** [comment]
> Sorry, I feel like I'm missing something important - the tests that involve solving the problem don't appear to pass when running them on my computer (i.e., I see the `java.lang.NoSuchMethodError: <init>` error).

Do you still have this issue ?

**Comment by jeffreyhanson** [comment]
Nah - you've fixed it - thanks!

**Pull request merged**
