### PR TITLE
Update GitHub Actions CI

### PR DESCRIPTION
**Pull request by jeffreyhanson**
This PR aims to improve continuous testing for package. It aims to add multiple operating systems, examine different package check settings to help mimic the different checks run on CRAN, and checks for URLs (because CRAN checks URLs in package documentation on submission).

Please note that this is a draft PR - I would like to ensure that it actually works before we merge it :)

### CODE REVIEW

**Comment by jeffreyhanson** [comment]
Hmm, it would appear that the version of the package in the main branch isn't passsing the package checks (e.g. due to codoc warnings). I suggest we fix that stuff working first before working more on this PR - otherwise we'll (or at least me?) get ~10 emails about build failures per commit. Is that ok?

**Comment by dimitri-justeau** [comment]
> Hmm, it would appear that the version of the package in the main branch isn't passsing the package checks (e.g. due to codoc warnings). I suggest we fix that stuff working first before working more on this PR - otherwise we'll (or at least me?) get ~10 emails about build failures per commit. Is that ok?

Yep let's fix this, I'll have a look at what not working right now !

**Comment by dimitri-justeau** [comment]
Ok I figured out what was happening:

 - I did not modify `add_locked_up_constraint` documentation along with the last modification, this was the source of the warning.
 - There was also a bug linked to terra::sources, whose default behaviour has changed since commit https://github.com/rspatial/terra/commit/45c973d279c2b4cff55d2730d193500227d25dab#diff-3e34da4a53ec643c2fd8c7338d0c6c6d90bdb0400bb53364ab78963e5fc0cb10

GitHub action for Ubuntu build is now ok !

**Comment by jeffreyhanson** [comment]
Aweosme - thanks! I'll see if I can get these CI tests working now.

**Pull request merged**
